INSERT INTO coach(train_no,coach_no,type_of) VALUES (12957,'A1','First AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12957,'A2','First AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12957,'A3','Second AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12957,'A4','Second AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12957,'A5','Second AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12957,'A6','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12957,'A7','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12957,'A8','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12957,'A9','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12957,'A10','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12957,'C1','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12957,'C2','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12957,'C3','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12957,'C4','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12957,'C5','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (NULL,NULL,NULL);
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12009,'C1','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12009,'C2','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12009,'C3','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12009,'C4','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12009,'C5','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12009,'C6','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12009,'C7','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12009,'C8','Executive Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12009,'C9','Executive Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12009,'C10','Executive Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (NULL,NULL,NULL);
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12604,'S1','Sleeper class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12604,'S2','Sleeper class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12604,'S3','Sleeper class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12604,'S4','Sleeper class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12604,'S5','Sleeper class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12604,'S6','Sleeper class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12604,'S7','Sleeper class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12604,'G1','General');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12604,'G2','General');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12604,'G3','General');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12604,'A1','First AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12604,'A2','Second AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12604,'A3','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12604,'A4','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12604,'C1','Chair Car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12045,'C1','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12045,'C2','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12045,'C3','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12045,'C4','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12045,'C5','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12045,'C6','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12045,'C7','AC Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12045,'C8','Executive Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12045,'C9','Executive Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12045,'C10','Executive Chair car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'A1','First AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'A2','Second AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'A3','Second AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'A4','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'A5','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'S1','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'S2','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'S3','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'S4','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'S5','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'S6','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'S7','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'S8','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'G1','General');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'G2','General');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'G3','General');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'SS1','Second Seating');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'SS2','Second Seating');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12779,'C1','AC Chair Car');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12424,'A1','First AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12424,'A2','First AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12424,'A3','Second AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12424,'A4','Second AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12424,'A5','Second AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12424,'A6','Second AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12424,'A7','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12424,'A8','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12424,'A9','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12424,'A10','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12424,'A11','Economy AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12424,'A12','Economy AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12267,'A1','Economy AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12267,'A2','First AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12267,'A3','Second AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12267,'A4','Second AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12267,'A5','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12267,'A6','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12267,'A7','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12267,'A8','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12267,'A9','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12267,'A10','Economy AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12267,'A11','Economy AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12297,'A1','Economy AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12297,'A2','First AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12297,'A3','Second AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12297,'A4','Second AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12297,'A5','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12297,'A6','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12297,'A7','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12297,'A8','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12297,'A9','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12297,'A10','Economy AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12297,'A11','Economy AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12345,'A1','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12345,'A2','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12345,'S1','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12345,'S2','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12345,'S3','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12345,'S4','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12345,'S5','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12345,'S6','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12345,'S7','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12345,'S8','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12345,'S9','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12345,'S10','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12345,'G1','General');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12345,'G2','General');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12345,'SS1','Second Seating');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12345,'SS2','Second Seating');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12345,'SS3','Second Seating');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (11464,'S1','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (11464,'S2','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (11464,'S3','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (11464,'S4','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (11464,'S5','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (11464,'S6','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (11464,'S7','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (11464,'A1','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (11464,'A2','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (11464,'SS1','Second Seating');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (11464,'SS2','Second Seating');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12979,'A1','First AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12979,'A2','Second AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12979,'A3','Second AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12979,'A4','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12979,'A5','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12979,'A6','Third AC');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12979,'S1','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12979,'S2','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12979,'S3','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12979,'S4','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12979,'S5','Sleeper Class');
INSERT INTO coach(train_no,coach_no,type_of) VALUES (12979,'C1','Chair car');
