INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Ahmedabad',12957,1,NULL,'17:40');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Ahmedabad',12009,1,'12:45',NULL);
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Ahmedabad',12267,2,'05:50',NULL);
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Ahmedabad',12297,1,NULL,'22:30');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Ahmedabad',11464,4,'08:00','08:15');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Abu Road',12957,2,'20:45','20:50');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Ajmer',12957,3,'00:50','00:55');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Jaipur',12957,7,'02:45','02:50');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Mumbai Central',12009,1,'06:25',NULL);
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Mumbai',12267,2,NULL,'23:25');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Surat',12009,1,'09:31','09:36');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Surat',12979,4,'20:33','20:38');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Vadodara',12009,4,'11:02','11:07');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Vadodara',11464,5,'05:20','05:50');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Vadodara',12979,3,'22:32','22:48');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Nadiad',12009,4,'11:47','11:49');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Secunderabad',12604,1,NULL,'17:50');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Guntar',12604,1,NULL,'17:50');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Tenali',12604,2,'23:10','23:12');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Nidubrolu',12604,2,'23:30','23:31');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Kavali',12604,2,'01:37','01:38');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Chennai',12604,3,'05:55',NULL);
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('New Delhi',12045,5,NULL,'19:15');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('New Delhi',12957,5,'07:30',NULL);
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('New Delhi',12779,4,'06:20',NULL);
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('New Delhi',12424,2,NULL,'13:55');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Sonipat',12045,4,'19:59','20:00');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Karnal',12045,8,'20:48','20:50');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Ambala cantt',12045,6,'21:58','22:00');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Chandigarh',12045,4,'22:45',NULL);
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Vasco-Da-Gama',12779,2,NULL,'15:10');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Madgoan',12779,1,'15:45','15:50');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Kulem',12779,3,'16:30','16:35');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Castle rock',12779,2,'17:35','17:40');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Londa',12779,3,'18:35','18:40');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Belagavi',12779,4,'19:45','19:50');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Miraj',12779,5,'22:25','22:30');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Satara',12779,3,'00:35','00:40');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Pune',12779,3,'03:55','04:10');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Pune',12297,3,'07:10',NULL);
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Daund',12779,1,'05:35','05:50');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Manmad',12779,1,'10:15','10:20');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Bhusaval',12779,1,'12:40','12:55');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Khandwa',12779,2,'14:55','15:00');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Itarsi',12779,2,'17:30','17:35');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Bhopal',12779,1,'19:30','19:40');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Jhansi',12779,2,'23:50','23:58');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Gwalior',12779,1,'01:10','01:15');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Agra',12779,1,'03:00','03:05');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Kanpur',12424,2,'18:34','18:39');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Mughal Sarai',12424,1,'22:45','22:55');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Patna',12424,2,'02:00','02:10');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Barauni',12424,1,'04:25','04:45');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Katihar',12424,2,'07:40','07:50');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Jalpaiguri',12424,1,'10:45','11:05');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Jalpaiguri',12345,2,'01:40','02:00');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Guwahati',12424,2,'17:30',NULL);
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Guwahati',12345,2,'09:35',NULL);
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Howrah',12345,3,NULL,'15:50');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Bolpur',12345,1,'17:53','17:58');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Malda',12345,1,'21:30','21:45');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Jabalpur',11464,2,NULL,'12:00');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Itarsi',11464,2,'16:00','16:15');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Bhopal',11464,2,'18:35','18:45');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Ujjain',11464,1,'22:45','22:55');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Nagda',11464,2,'23:50','23:55');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Ratlam',11464,2,'01:05','01:20');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Rajkot',11464,3,'13:10','13:17');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Somnath',11464,4,'18:00',NULL);
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Bandra',12979,1,NULL,'15:45');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Vapi',12979,1,'18:27','18:29');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Valsad',12979,2,'19:31','19:33');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Ratlam',12979,2,'02:45','02:55');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Kota',12979,2,'06:30','06:35');
INSERT INTO station(station_name,train_no,platform_number,arrival_time,departure_time) VALUES ('Jaipur',12979,3,'10:45',NULL);
