INSERT INTO `indian_railways`.`train` (`train_name`, `train_number`, `intial_station`, `final_station`) VALUES (' Swarna rajdhani', '12957', 'Ahmedabad', 'New Delhi');
INSERT INTO `indian_railways`.`train` (`train_name`, `train_number`, `intial_station`, `final_station`) VALUES ('Shatabdi', '12009', 'Mumbai Central', 'Ahmedabad');
INSERT INTO `indian_railways`.`train` (`train_name`, `train_number`, `intial_station`, `final_station`) VALUES ('Hyderabad-Chennai Central SF', '12604', 'Secunderabad', 'Chennai');
INSERT INTO `indian_railways`.`train` (`train_name`, `train_number`, `intial_station`, `final_station`) VALUES ('Shatabdi', '12045', 'New Delhi', 'Chandigarh');
INSERT INTO `indian_railways`.`train` (`train_name`, `train_number`, `intial_station`, `final_station`) VALUES ('Goa Express', '12779', 'Vasco-Da-Gama', 'New Delhi');
INSERT INTO `indian_railways`.`train` (`train_name`, `train_number`, `intial_station`, `final_station`) VALUES ('Rajdhani', '12424', 'New delhi', 'Guwahati');
INSERT INTO `indian_railways`.`train` (`train_name`, `train_number`, `intial_station`, `final_station`) VALUES ('Duranto Mumbai', '12267', 'Mumbai', 'Ahmedabad');
INSERT INTO `indian_railways`.`train` (`train_name`, `train_number`, `intial_station`, `final_station`) VALUES ('Duranto Pune', '12297', 'AhmedabAD', 'Pune');
INSERT INTO `indian_railways`.`train` (`train_name`, `train_number`, `intial_station`, `final_station`) VALUES ('Saraighat Express', '12345', 'Howrah', 'Guwahati');
INSERT INTO `indian_railways`.`train` (`train_name`, `train_number`, `intial_station`, `final_station`) VALUES ('jabalpur-somnath express', '11464', 'Jabalpur', 'Somnath');
INSERT INTO `indian_railways`.`train` (`train_name`, `train_number`, `intial_station`, `final_station`) VALUES ('Jaipur superfast express', '12979', 'Bandra', 'Jaipur');
